machine:
  kubelet:
    image: ghcr.io/siderolabs/kubelet:v1.35.0
cluster:
  apiServer:
    image: registry.k8s.io/kube-apiserver:v1.35.0
  controllerManager:
    image: registry.k8s.io/kube-controller-manager:v1.35.0
  scheduler:
    image: registry.k8s.io/kube-scheduler:v1.35.0
  proxy:
    image: registry.k8s.io/kube-proxy:v1.35.0
