# Schematic Ready
# Your image schematic ID is: aaafc937bd215b9f17980fe8ff2ea197f835e06c57aa46a01d3dc2e6e8f494d8
# customization:
#     systemExtensions:
#         officialExtensions:
#             - siderolabs/btrfs
#             - siderolabs/iscsi-tools
#             - siderolabs/qemu-guest-agent
#             - siderolabs/util-linux-tools
# First Boot
# Here are the options for the initial boot of Talos Linux on Nocloud:

# Disk Image
# https://factory.talos.dev/image/aaafc937bd215b9f17980fe8ff2ea197f835e06c57aa46a01d3dc2e6e8f494d8/v1.12.1/nocloud-amd64.raw.xz
# ISO
# https://factory.talos.dev/image/aaafc937bd215b9f17980fe8ff2ea197f835e06c57aa46a01d3dc2e6e8f494d8/v1.12.1/nocloud-amd64.iso
# PXE boot (iPXE script)
# https://pxe.factory.talos.dev/pxe/aaafc937bd215b9f17980fe8ff2ea197f835e06c57aa46a01d3dc2e6e8f494d8/v1.12.1/nocloud-amd64
# Initial Installation
# For the initial installation of Talos Linux (not applicable for disk image boot), add the following installer image to the machine configuration:
# factory.talos.dev/nocloud-installer/aaafc937bd215b9f17980fe8ff2ea197f835e06c57aa46a01d3dc2e6e8f494d8:v1.12.1

# Upgrading Talos Linux
# To upgrade Talos Linux on the machine, use the following image:
# factory.talos.dev/nocloud-installer/aaafc937bd215b9f17980fe8ff2ea197f835e06c57aa46a01d3dc2e6e8f494d8:v1.12.1
customization:
    systemExtensions:
        officialExtensions:
            - siderolabs/btrfs
            - siderolabs/iscsi-tools
            - siderolabs/qemu-guest-agent
            - siderolabs/util-linux-tools